# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bruno P. Kinoshita
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Kinow
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kinoshita.eti.br" # the base hostname & protocol for your site, e.g. http://example.com

destination: "./build"

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

whitelist:
  - jekyll-feed
  - jekyll-seo-tag

show_excerpts: true
excerpt_separator: "<!--more-->"

exclude:
  - .idea
  - art-sprites.sh
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - scripts
  - '**/*.qgz'
  - .bundle
  - .git
  - vendor

collections:
  pages:
    output: true
    permalink: /:path/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
envs: development

permalink: /:year/:month/:day/:title:output_ext
timezone: Pacific/Auckland

sass:
  style: compact # possible values: nested expanded compact compressed

pagination:
  enabled: true
  debug: false
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
