baseURL = 'https://kinoshita.eti.br'
languageCode = 'en-us'
title = "kinow"
theme = 'kinoshita.eti.br'
# sectionPagesMenu = "main"
disablePathToLower = false
uglyurls = true
buildFuture = true

rssLimit = 20
copyright = "Bruno P. Kinoshita All rights reserved"

contentDir = "content"
publishDir = "public"
enableRobotsTXT = true
disableBrowserError = true
timeout = 3000

ignoreFiles = [
  "./.github",
  "./_data",
  "./data",
  "./scripts"
]

# Highlighting config. See https://help.farbox.com/pygments.html
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsStyle = "emacs"

# Enable Git variables like commit, lastmod
enableGitInfo = true

[pagination]
pagerSize = 5

[menu]
  [[menu.main]]
    name = "About"
    pre = "about"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Portfolio"
    pre = "portfolio"
    url = "/portfolio/"
    weight = 3

[permalinks]
  posts = '/:year/:month/:day/:title'

[markup]
  [markup.highlight]
  style = 'xcode'
[markup.goldmark.renderer]
  unsafe= true

[blackfriday]
# hrefTargetBlank = true # We don't want everything opened in a new window
  fractions = false

[frontmatter]
  date = ["date", ":filename", "publishDate", "lastmod"]

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "RSS"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss+xml"
    baseName = "feed"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[params]
  description = "Personal website of Bruno P. Kinoshita, kinow"
  images = ["/assets/photos/about/2023-me-closeup.png"]
  title = "Personal website of Bruno P. Kinoshita, kinow"
  copyright = "Bruno P. Kinoshita All rights reserved"
  [params.social]
    facebook_admin = 'bruno.kinoshita'
    twitter = 'kinow'
  [params.author]
    name = 'Bruno P. Kinoshita'
