baseURL = 'https://kinoshita.eti.br'
languageCode = 'en-us'
title = "kinow"
theme = 'kinoshita.eti.br'
# sectionPagesMenu = "main"
disablePathToLower = false
uglyurls = true

[menu]
  [[menu.main]]
    name = "About"
    pre = "about"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Portfolio"
    pre = "portfolio"
    url = "/portfolio/"
    weight = 3

[permalinks]
  posts = '/:year/:month/:day/:title'
