baseURL = 'https://kinoshita.eti.br'
languageCode = 'en-us'
title = "kinow"
theme = 'kinoshita.eti.br'
# sectionPagesMenu = "main"
disablePathToLower = false
uglyurls = true
buildFuture = true

rssLimit = 20
copyright = "Bruno P. Kinoshita All rights reserved"

[author]
  name = "Bruno P. Kinoshita"
#  email = "[email protected]"

paginate = 5

contentDir = "content"
publishDir = "public"
enableRobotsTXT = true
disableBrowserError = true
timeout = 3000

disableKinds = ["taxonomy", "taxonomyTerm"]
ignoreFiles = [
  ".github",
  "_data",
  "data",
  "scripts"
] # No files to ignore

# Highlighting config. See https://help.farbox.com/pygments.html
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsStyle = "emacs"

# Enable Git variables like commit, lastmod
enableGitInfo = true

[menu]
  [[menu.main]]
    name = "About"
    pre = "about"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Portfolio"
    pre = "portfolio"
    url = "/portfolio/"
    weight = 3

[permalinks]
  posts = '/:year/:month/:day/:title'

[markup.goldmark.renderer]
unsafe= true

[blackfriday]
# hrefTargetBlank = true # We don't want everything opened in a new window
fractions = false

[frontmatter]
date = ["date", ":filename", "publishDate", "lastmod"]

[markup]
  [markup.highlight]
    style = 'xcode'

[sitemap]
changefreq = 'monthly'
filename = 'sitemap.xml'
priority = 0.5

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"
