name: CV
on:
  push:
    branches:
      - master
    paths:
      - 'scripts/cv/**'
  pull_request:
    paths:
      - 'scripts/cv/**'
  workflow_dispatch:
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
          cache: 'pip'
      - name: Dependencies
        run: |
          cd ./scripts/cv/
          pip install -r requirements.txt
      - name: Build
        run: |
          INPUT_FILENAME=cv_backend.yaml make clean all
          ls build/
