name: GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SCM
        uses: actions/checkout@v2
      - name: Build
        uses: meitar/jekyll-builder-for-github-pages-action@builder/3.8
        env:
          JEKYLL_UID: 0
          JEKYLL_GID: 0
        with:
          secret_gh_pages_api_token: ${{ secrets.ACCESS_TOKEN }}

