name: Test GitHub Pages pull request
on:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: SCM
        uses: actions/checkout@v7
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.159.2'
          extended: true
      - name: Build
        run: hugo --minify
      - name: List files
        run: ls ./public
